### ISSUE TITLE
Improve F-OH and verify on latest Oniro version

### ISSUE THREAD

**Issue by frankplus** [eclipse-oniro4openharmony/oniro-planning#4]
Build F-OH and rebase to Oniro based  on OpenHarmony 4.1 or 5.0

**Comment by imansmallapple** [comment]
1. Fixed code with incompatible issue.
2. Added loading component during connecting server/website
3. Added no internet UI component when connection fails
4. Added short animation when open the app
5. Changed 'Settings->about oniro/author' logo size
6. Changed repo links with oniro in 'About Oniro' page
7. Replaced 'about app' with 'Oniro plateform' in 'About Oniro' page

**Comment by frankplus** [comment]
The updates are pushed here: https://github.com/eclipse-oniro4openharmony/f-oh
